sudo: required
services:
  - docker

before_install:
  - docker build -t 131231231231312312/kuber-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true 131231231231312312/kuber-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-cuber"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-551483742030"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
